"""3 start

Revision ID: 85389d6f4708
Revises: 
Create Date: 2022-03-22 22:41:41.089380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85389d6f4708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
