"""First migration

Revision ID: 93b77cf313e0
Revises: 
Create Date: 2022-03-31 14:03:31.310435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b77cf313e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_table('choice',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('value', sa.Boolean(), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['question.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_choice_id'), 'choice', ['id'], unique=False)
    op.create_table('result',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.Column('answer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['answer_id'], ['choice.id'], ),
                    sa.ForeignKeyConstraint(
                        ['question_id'], ['question.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_result_id'), 'result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_choice_id'), table_name='choice')
    op.drop_table('choice')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
