"""3 start

Revision ID: 940afd99c5c2
Revises: 7d3bec95f4b1
Create Date: 2022-03-22 23:08:06.232085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940afd99c5c2'
down_revision = '7d3bec95f4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
